# Generated by Django 2.1.7 on 2019-05-17 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responsible', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materials_update',
            old_name='title',
            new_name='location',
        ),
    ]
