# Generated by Django 2.1.7 on 2019-03-10 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190310_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimage',
            old_name='Post',
            new_name='post',
        ),
    ]
