# Generated by Django 2.1.7 on 2019-03-12 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190312_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='subheader',
            new_name='subtitle',
        ),
    ]
