# Generated by Django 2.1.7 on 2019-03-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190312_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subheader1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='subheader2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='subtitle',
            field=models.TextField(blank=True, null=True),
        ),
    ]
