# Generated by Django 2.1.7 on 2019-04-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190312_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subheader3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
